apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 60Gi
